---
title: "Create Codelists"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(here)
library(dbplyr)
library(readr)
library(bigrquery)
library(DBI)

source(here("scripts/connect_bigquery.R"))
```

```{r}
sql_dmd_product <- dbplyr::sql(
"SELECT 'vmp' AS type, vmp.id, bnf_code, vmp.nm, ing.nm AS ingredient, ddd.ddd 
FROM dmd.vmp
INNER JOIN dmd.vpi AS vpi ON vmp.id = vpi.vmp 
INNER JOIN dmd.ing as ing ON ing.id = vpi.ing 
LEFT JOIN dmd.ddd on vmp.id = ddd.vpid

ORDER BY type, nm")
```


```{r cache=TRUE}

db_sql_dmd_product <- dplyr::tbl(conn_ebm_scmd, sql_dmd_product)
db_sql_dmd_product

```

```{r}


# set name of codelist for exporting file
# codelist_name = "narcolepsy"

# import or paste list of vtms (Virtual Therapeutic Moieties / Ingredients) by name
# names = ['Sodium Oxybate', 'Pitolisant', 'Solriamfetol', 'Modafinol', 'Dexamfetamine', 'Methylphenidate']

# from ebmdatalab import bq
# from termcolor import colored
# import os
# import pandas as pd
# import numpy as np
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_colwidth', None)
# 5-Methoxypsoralen
db_sql_dmd_product %>% 
  filter(ingredient %LIKE% c("%Methoxypsoralen"))
```

